export class FlightDataModel {
    id!: string;
    providerId!: string;
    providerName!: string;
    tripTypeId!: string;
    cabinTypeId!: string;
    groupAirlineCode!: string;
    airlineLogo!: string;
    airlineName!: string;
    airlineCode!: string;
    airlineId!: string;
    airlineNumber!: string;
    airCraftId!: string;
    airCraftCode!: string;
    airCraftName!: string;
    departureDate!: string;
    arrivalDate!: string;
    departureTime!: string;
    arrivalTime!: string;
    departureCityId!: string;
    departureCityCode!: string;
    departureCity!: string;
    arrivalCityId!: string;
    arrivalCityCode!: string;
    arrivalCity!: string;
    differenceTime!: string;
    adult!: number;
    child!: number;
    infant!: number;
    stop!: number;
    stopAllCity!: string;
    tooltipData!: string;
    adjustment!: number;
    domestic: boolean = false;
    flightRouteTypeId!: string;
    lastTicketDate!: string;
    lastTicketTime!: string;
    baggageAdult!: string;
    baggageChild!: string;
    baggageInfant!: string;
    cabinAdult!: string;
    cabinChild!: string;
    cabinInfant!: string;
    instantEnable!: string;
    airlinesRouteEnableId!: string;
    btnLoad: boolean = false;
    isAgentFare: boolean = false;
    refundable: boolean = false;
    fareBasisCode!: string;
    totalPrice!: number;
    totalDiscount!: number;
    markupInfo:any;
    discountInfo:any;
    clientFareTotal!: number;
    agentFareTotal!: number;
    gdsFareTotal!: number;
    
}
